if GetLocale() == "zhTW" then
_G["BINDING_HEADER_TOTEMTIMERSHEADER"] = "薩滿圖騰快捷列"
_G["BINDING_NAME_TOTEMTIMERSAIR"] = "施放空之圖騰技能"
_G["BINDING_NAME_TOTEMTIMERSAIRMENU"] = "開啟空之圖騰選單"
_G["BINDING_NAME_TOTEMTIMERSEARTH"] = "施放大地圖騰技能"
_G["BINDING_NAME_TOTEMTIMERSEARTHMENU"] = "開啟大地圖騰選單"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDLEFT"] = "左鍵點擊大地之盾"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDMIDDLE"] = "中鍵點擊大地之盾"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDRIGHT"] = "右鍵點擊大地之盾"
_G["BINDING_NAME_TOTEMTIMERSEARTHSHIELDBUTTON4"] = "按鍵4點擊大地之盾"
_G["BINDING_NAME_TOTEMTIMERSFIRE"] = "施放火焰圖騰技能"
_G["BINDING_NAME_TOTEMTIMERSFIREMENU"] = "開啟火焰圖騰選單"
_G["BINDING_NAME_TOTEMTIMERSWATER"] = "施放水之圖騰技能"
_G["BINDING_NAME_TOTEMTIMERSWATERMENU"] = "開啟水之圖騰選單"
_G["BINDING_NAME_TOTEMTIMERSWEAPONBUFF1"] = "武器增溢1"
_G["BINDING_NAME_TOTEMTIMERSWEAPONBUFF2"] = "武器增溢2"

_G["BINDING_NAME_TOTEMTIMERSSET1"] = "組合 1"
_G["BINDING_NAME_TOTEMTIMERSSET2"] = "組合 2"
_G["BINDING_NAME_TOTEMTIMERSSET3"] = "組合 3"
_G["BINDING_NAME_TOTEMTIMERSSET4"] = "組合 4"
_G["BINDING_NAME_TOTEMTIMERSSET5"] = "組合 5"
_G["BINDING_NAME_TOTEMTIMERSSET6"] = "組合 6"
_G["BINDING_NAME_TOTEMTIMERSSET7"] = "組合 7"
_G["BINDING_NAME_TOTEMTIMERSSET8"] = "組合 8"
_G["BINDING_NAME_TOTEMTIMERSCLOSE"] = "關閉所有選單"
_G["BINDING_NAME_TOTEMTIMERSMULTICAST"] = "作用中的多重施法 (元素呼喚等)"
_G["BINDING_NAME_TOTEMTIMERSMULTICASTMENU"] = "打開多重施法選單"

end 

local L = LibStub("AceLocale-3.0"):NewLocale("TotemTimers", "zhTW")
if not L then L = {} end

L["Air Button"] = "風之圖騰"
L["Cooldown"] = "冷卻"
L["Ctrl-Leftclick to remove weapon buffs"] = "Ctrl+左鍵移除武器增益"
L["Delete Set"] = "是否要刪除圖騰組合 %s?"
L["Earth Button"] = "大地圖騰"
L["Fire Button"] = "火焰圖騰"
L["Leftclick to cast %s"] = "左鍵施放%s"
L["Leftclick to cast spell"] = "左鍵施放法術"
L["Leftclick to load totem set"] = "左鍵載入圖騰組合"
L["Leftclick to open totem set menu"] = "左鍵打開圖騰組合選單"
L["Long Cooldown"] = "長冷卻時間"
L["Maelstrom Notifier"] = "漩渦就緒!"
L["Middleclick to cast %s"] = "中鍵施放%s"
L["Next leftclick casts %s"] = "下次點左鍵施放%s"
L["Reset"] = "TotemTimers 已重置！"
L["Rightclick to assign both %s and %s to leftclick"] = "右鍵分配%s和%s到左鍵"
L["Rightclick to assign spell to leftclick"] = "右鍵分配法術到左鍵"
L["Rightclick to assign totem to timer button"] = "右鍵分配圖騰到計時器按鈕"
L["Rightclick to cast %s"] = "右鍵施放%s"
L["Rightclick to delete totem set"] = "右鍵圖騰設置"
L["Rightclick to save active totem configuration as set"] = "右鍵將作用中的圖騰設定儲存為組合"
L["Shield removed"] = "已移除護盾"
L["Shift-Rightclick to assign spell to middleclick"] = "Shift+右鍵分配法術到中鍵"
L["Shift-Rightclick to assign spell to rightclick"] = "Shift+右鍵分配法術到右鍵"
L["Totem Destroyed"] = "圖騰已摧毀"
L["Totem Expired"] = "圖騰到期了"
L["Totem Expiring"] = "圖騰快到期"
L["Water Button"] = "水之圖騰"

-- 自行加入
L["Ctrl-Rightclick to disable totem for %s"] = "Ctrl+右鍵停用%s圖騰"
L["Ctrl-Rightclick to enable element for %s"] = "Ctrl+右鍵啟用%s元素"
L["Rightclick to assign to weapon button leftclick"] = "右鍵分配到左鍵點武器按鈕"
L["Shift-Rightclick to assign to weapon button rightclick"] = "Shift+右鍵分配到右鍵點武器按鈕"
